### ISSUE TITLE
Plugin does not work with Grails 3.3.0.M2

### ISSUE THREAD

**Issue by sdelamo** [sbglasius/external-config#11]
## Steps to reproduce

Create an app with Grails 3.3.0.M2 

Add the dependency:  `compile "org.grails.plugins:external-config:1.1.0"`

Run `gradlew bootRun`

```
Exception in thread "main" java.lang.AbstractMethodError
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at externalconfig.Application.main(Application.groovy:8)
:bootRun FAILED

```

**Comment by sdelamo** [comment]
I tested with the build-snapsnoht without success either
