### ISSUE TITLE
external-config plugin is compiled with Java8

### ISSUE THREAD

**Issue by andersaaberg** [sbglasius/external-config#17]
Grails3 supports Java7 (see http://docs.grails.org/latest/guide/gettingStarted.html) which is a requirement from my customer, but the external-config plugin is compiled with Java8 and that prevents us from using it.

I get the following error when using 'org.grails.plugins:external-config:1.1.1':
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.boot.SpringApplicationRunListener : grails.plugin.externalconfig.ExternalConfigRunListener
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:425)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:404)
        at org.springframework.boot.SpringApplication.getRunListeners(SpringApplication.java:390)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at myapp.Application.main(Application.groovy:8)
Caused by: java.lang.UnsupportedClassVersionError: grails/plugin/externalconfig/ExternalConfigRunListener : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:417)
        ... 11 more
:bootRun FAILED
```

I verified this by looking up the class in the external-config-1.1.1.jar:
file ExternalConfigRunListener.class
ExternalConfigRunListener.class: compiled Java class data, version 52.0 (Java 1.8)

Solution:
I downloaded the latest external-config plugin source to my local machine and added "sourceCompatibility=1.7" to build.gradle such that the produced artifact is Java7 compatible regardless of jdk version used to produce it. All the plugin tests ran (gradle check) without issues and I was able to use the external-config plugin in my application (from mavenLocal repository). I am happy to help with creating a new release, but I could use some guidance on how to release it. I have setup binTray (user: andersaaberg), but "gradle clean bintrayUpload" yields "HTTP/1.1 403 Forbidden".

In general, it would be very helpful with a mechanism to ensure that grails plugins are released with Java 7 or clearly marked as requiring a later Java version - maybe we can use some kind of rule to ensure that sourceCompatibility is always set for plugins?

**Comment by andersaaberg** [comment]
I realised that Bintray is only for publishing the plugin to https://plugins.grails.org and not to update the actual plugin code, so I made a normal pull request instead: https://github.com/sbglasius/external-config/pull/18

**Comment by andersaaberg** [comment]
I can see that Travis Continious Integration intends to use Java7 for releases ("jdk_switcher" @ https://travis-ci.org/sbglasius/external-config/builds/211794021), but it still fails to produce Java7 artifacts so that is the root cause of this issue. I hope that someone can fix that by debugging the Travis process - I cannot reproduce the problem locally.

Setting sourceCompatibility is still a good idea, because it will prevent people from committing Java8 specific code and first realizing the mistake when they have pushed it and Travis Continious Integration fails.

**Comment by andersaaberg** [comment]
We also need to update GroovyConfigWriter which this plugin depends on: https://github.com/virtualdogbert/GroovyConfigWriter/issues/3
