### ISSUE TITLE
Grails 4: Issue on startup with Grails 4 and JDK 11

### ISSUE THREAD

**Issue by erichelgeson** [sbglasius/external-config#35]
Grails 4 master & JDK 11.0.1 zulu

Example:
https://github.com/erichelgeson/grails4/compare/eric/externalConfig

```
2019-01-14 16:50:38.293 ERROR --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.AbstractMethodError: Receiver class grails.plugin.externalconfig.ExternalConfigRunListener does not define or inherit an implementation of the resolved method abstract started(Lorg/springframework/context/ConfigurableApplicationContext;)V of interface org.springframework.boot.SpringApplicationRunListener.
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:95)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:447)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:434)
	at four.Application.main(Application.groovy:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

**Comment by kevintanhongann** [comment]
What was the fix? I'm hit with the same issue when I used Grails external-config v1.4.0. 

Can someone help point me to the right direction?

**Comment by pendyala** [comment]
> What was the fix? I'm hit with the same issue when I used Grails external-config v1.4.0.
> 
> Can someone help point me to the right direction?

Please use version 2.0.0
