### ISSUE TITLE
Grails 3 Startup Fails on Windows

### ISSUE THREAD

**Issue by dvkvarma** [sbglasius/external-config#36]
Grails Startup is failing on windows with the following exception.

```
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at grails.plugin.externalconfig.ExternalConfigRunListener.handleWildcardLocation(ExternalConfigRunListener.groovy:91)
	at grails.plugin.externalconfig.ExternalConfigRunListener$_getLocations_closure1.doCall(ExternalConfigRunListener.groovy:79)
	at grails.plugin.externalconfig.ExternalConfigRunListener$_getLocations_closure1.call(ExternalConfigRunListener.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:3462)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:3437)
```

Issue with Separator being \ in windows. \ is being considered as a regular expression.

https://github.com/sbglasius/external-config/blob/0b70d31443248be28da2404c53f64d770be1150a/src/main/groovy/grails/plugin/externalconfig/ExternalConfigRunListener.groovy#L91

Probably replacing split with tokenize might solve the issue.

**Comment by verglor** [comment]
Hi @sbglasius, please, could you release a new version with this patch ?
