### ISSUE TITLE
Cannot Start App In Grails 4

### ISSUE THREAD

**Issue by dustindclark** [sbglasius/external-config#44]
Getting the following error after installing 1.4.0 and attempting to run a Grails 4 app:

```
2019-08-11 13:05:55.038 ERROR --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.AbstractMethodError: null
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:71)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:97)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:458)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:445)
	at com.collegeswapshop.Application.main(Application.groovy:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

And then later in the logs:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field urlMappingsHolder in org.grails.web.mapping.DefaultLinkGenerator required a bean of type 'grails.web.mapping.UrlMappingsHolder' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
	- @org.springframework.beans.factory.annotation.Qualifier(value=grailsUrlMappingsHolder)


Action:

Consider defining a bean of type 'grails.web.mapping.UrlMappingsHolder' in your configuration.
```

Still digging and with post a workaround if I find one.

**Comment by dustindclark** [comment]
May be related to https://github.com/sbglasius/external-config/issues/35, but I'm using Java 8 (specifically jdk1.8.0_192.jdk).

**Comment by dustindclark** [comment]
Looks like I just needed to be on 2.0.0 of the plugin.  Please update the docs if that's the required version for Grails 4.  Thanks.
